# Generated by Django 3.0.2 on 2020-01-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200127_0616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title', 'price', 'start_date'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.ManyToManyField(to='courses.Teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_teacher',
            field=models.ManyToManyField(to='courses.Teacher'),
        ),
    ]
