# Generated by Django 3.0.2 on 2020-02-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200201_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
