# Generated by Django 3.0.2 on 2020-02-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200206_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_teacher',
            field=models.ManyToManyField(blank=True, to='courses.Teacher'),
        ),
    ]
