# Generated by Django 3.0.2 on 2020-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200208_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='durance',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_program',
            field=models.TextField(blank=True, verbose_name='Программа курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_teacher',
            field=models.ManyToManyField(blank=True, to='courses.Teacher', verbose_name='Преподаватели курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество уроков'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата проведения'),
        ),
    ]
