# Generated by Django 3.0.2 on 2020-01-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_lessons',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, verbose_name='Домашнее задание к уроку'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='durance',
            field=models.IntegerField(default='0', verbose_name='Длительность, мин'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
