# Generated by Django 3.0.2 on 2020-02-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200206_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_teacher',
            field=models.ManyToManyField(blank=True, to='courses.Teacher'),
        ),
    ]
