# Generated by Django 3.0.2 on 2020-01-27 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200127_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['title'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
