# Generated by Django 3.0.2 on 2020-02-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20200218_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='accessed_courses',
            field=models.ManyToManyField(blank=True, to='courses.Course'),
        ),
    ]
