# Generated by Django 3.0.2 on 2020-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20200218_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения'),
        ),
    ]
