# Generated by Django 3.0.2 on 2020-02-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
